# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MolSSI Education
email: education@molssi.org
description: >- # this means to ignore newlines until "baseurl:"
  A website for MolSSI Education.
repository: molssi-education/education.molssi.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "education.molssi.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MolSSI_NSF
github_username:  molssi-education

# Build settings
markdown: CommonMarkGhPages
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
# define the navbar link
header_pages:
  - index.md
  - resources.md
  - events.md
  - calendar.md
  - request.md
  - map.md

social-links:
  - github: MolSSI-Education
  - twitter: MolSSI_NSF
  - linkedin: molecular-sciences-software-institute

<<<<<<< HEAD
=======
social-links:
  - github: MolSSI-Education
  - twitter: MolSSI_NSF
  - linkedin: molecular-sciences-software-institute

>>>>>>> 1904b682d0a20c3c85b80fb874223f5ccdea50f5
# Gems
plugins:
  - jekyll-octicons


# --- Events --- #
# Events are displayed via a collection to allow for single page generation.

# Collections
collections:
  events:
    output: true
    permalink: /:collection/:path

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
